In [1]:
import numpy as np;
import pandas as pd;

In [3]:
# Assume a directory in current working space with data. Not included bc I don't know if I'm allowed to put it up on Github.
df = pd.DataFrame.from_csv('data/train.csv')

/Users/flareon/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  if __name__ == '__main__':

In [4]:
df.head()

,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
Id,,,,,,,,,,,,,,,,,,,,,
0,24,0,0,5,247.30,2,0,4,17,1050,...,1,591.3,0,0.0,0,0,782.40,4,1458,0.8571
1,440875,1,1,0,37.65,1,1,0,45,1072,...,0,0.0,0,0.0,0,0,119.60,3,1511,0.0400
2,878242,2,0,1,93.73,1,0,2,54,1404,...,1,0.0,0,0.0,0,0,3248.00,5,1583,0.7407
3,1319841,3,0,0,95.88,0,0,0,86,1069,...,0,0.0,0,0.0,0,0,21.49,1,1489,0.1146
4,1757883,4,0,1,0.00,0,0,1,58,1034,...,0,0.0,0,0.0,0,0,640.80,4,1475,0.5217